---
abstract: 'The Do What The Fuck You Want To Public License, Version 2'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  Test::More: 0.89
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101240'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Software-License-WTFPL
recommends: {}
requires:
  Software::License: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Software-License-WTFPL
  homepage: http://search.cpan.org/dist/Software-License-WTFPL
  repository: git://github.com/rafl/software-license-wtfpl.git
version: 0.03
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@FLORA/@Filter/GatherDir'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@FLORA/@Filter/PruneCruft'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@FLORA/@Filter/ManifestSkip'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@FLORA/@Filter/MetaYAML'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::License
      name: '@FLORA/@Filter/License'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@FLORA/@Filter/Readme'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@FLORA/@Filter/PkgVersion'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@FLORA/@Filter/PodCoverageTests'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@FLORA/@Filter/PodSyntaxTests'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@FLORA/@Filter/ExtraTests'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@FLORA/@Filter/ExecDir'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@FLORA/@Filter/ShareDir'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@FLORA/@Filter/MakeMaker'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@FLORA/@Filter/Manifest'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@FLORA/@Filter/ConfirmRelease'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@FLORA/@Filter/UploadToCPAN'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@FLORA/MetaConfig'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@FLORA/MetaJSON'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@FLORA/MetaResources'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@FLORA/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@FLORA/AutoPrereq'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 2.101240
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 2.101240
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 2.101240
