---
abstract: 'The Do What The Fuck You Want To Public License, Version 2'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101240'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Software-License-WTFPL
recommends: {}
requires:
  Software::License: 0
resources:
  repository: git://github.com/rafl/software-license-wtfpl.git
version: 0.02
